### ISSUE TITLE
Add Fanout broadcast driver

### ISSUE THREAD

**Issue by garethtdavies** [fanout/laravel-grip#1]
Hi,

This is starting to look great but are there any plans (as this package is Laravel specific) to add a broadcast driver so we can simply broadcast our event data to Fanout? http://laravel.com/docs/5.1/events#broadcasting-events

In case you hadn't seen it this pull request contains the desired functionality: https://github.com/laravel/framework/pull/8705/files

**Comment by jkarneges** [comment]
Yup, I see a couple of ways to approach this.

1) Publish events using the basic "json-object" format for relaying through Fanout's Data Messaging service. This is essentially what the referenced pull request does. The feature may not belong in laravel-grip though, and instead in a laravel-fanout package (for comparison, we have a similar django-fanout package).

2) Publish events using the various GRIP formats (http-response, http-stream, ws-message). This is a little trickier because the formats aren't simply JSON. Probably there should be a way to specify a serialization class that takes a Laravel event object and converts it into the appropriate GRIP formats.

**Comment by garethtdavies** [comment]
Yup agreed. 1 is the approach I was talking about and it would make more sense in a laravel-fanout package.

**Comment by kbokarius** [comment]
laravel-fanout deployed per approach #1 above: https://github.com/fanout/laravel-fanout
